<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82" started-at="2019-08-06T09:33:57Z" finished-at="2019-08-06T09:33:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82" started-at="2019-08-06T09:33:57Z" finished-at="2019-08-06T09:33:57Z">
      <class name="testNGReport.iReporterReport.TestGuru99ForReporter">
        <test-method status="PASS" signature="testReporterOne()[pri:0, instance:testNGReport.iReporterReport.TestGuru99ForReporter@32d992b2]" name="testReporterOne" duration-ms="16" started-at="2019-08-06T16:33:57Z" description="testReporterOne" finished-at="2019-08-06T16:33:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReporterOne -->
        <test-method status="FAIL" signature="testReporterTwo()[pri:1, instance:testNGReport.iReporterReport.TestGuru99ForReporter@32d992b2]" name="testReporterTwo" duration-ms="2" started-at="2019-08-06T16:33:57Z" description="testReporterTwo" finished-at="2019-08-06T16:33:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNGReport.iReporterReport.TestGuru99ForReporter.testReporterTwo(TestGuru99ForReporter.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReporterTwo -->
      </class> <!-- testNGReport.iReporterReport.TestGuru99ForReporter -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
