<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="RailwayTestCaseRefactory.CreateAccountfRefactory" tests="5" time="12.873" ignored="0" failures="0" timestamp="05 Aug 2019 04:14:56 GMT" skipped="3" hostname="lgvn14828" errors="1">
  <testcase name="TC06" time="9.046" classname="RailwayTestCaseRefactory.CreateAccountfRefactory">
    <skipped/>
  </testcase> <!-- TC06 -->
  <testcase name="TC08" time="0.002" classname="RailwayTestCaseRefactory.CreateAccountfRefactory">
    <skipped/>
  </testcase> <!-- TC08 -->
  <testcase name="TC05" time="3.824" classname="RailwayTestCaseRefactory.CreateAccountfRefactory"/>
  <testcase name="afterMethod" time="0.000" classname="RailwayTestCaseRefactory.CreateAccountfRefactory">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at RailwayTestCaseRefactory.CreateAccountfRefactory.afterMethod(CreateAccountfRefactory.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="TC07" time="0.001" classname="RailwayTestCaseRefactory.CreateAccountfRefactory">
    <skipped/>
  </testcase> <!-- TC07 -->
</testsuite> <!-- RailwayTestCaseRefactory.CreateAccountfRefactory -->
